### ISSUE TITLE
File jumps up one line after save

### ISSUE THREAD

**Issue by upwebdesign** [bubenkoff/ExpandTabsOnSave-SublimeText#5]
@bubenkoff maybe I am the only one experiencing this, but since installing your package, every time I save a file, it jumps up to the next line. If I `command + s` consecutive times the file jumps up that many times as well. Other than that, your package is working great. Nice work!

Registered Build 3103

**Comment by bubenkoff** [comment]
hmm, never had that issue
can you please show what's in that file you save?
or it's just in every file?

**Comment by upwebdesign** [comment]
@bubenkoff Here is a Jing of what is happening: http://screencast.com/t/eJ3xGcpnPz6g
This is happening with every file. In the video, when you see it jump, its when I press `command + s`
Hope this helps!

**Comment by todthomson** [comment]
👍 I'm experiencing the same issue (on Windows, Mac & Linux) and always have been ever since installing this plugin. I just try my best to ignore it as I love the plugin too much 😎 It would be great to see it fixed however.

**Comment by bubenkoff** [comment]
@upwebdesign do you have `translate_tabs_to_spaces` on?

**Comment by bubenkoff** [comment]
the thing is, the whole code is just one line - to call the sublime's command to expand tabs...

**Comment by upwebdesign** [comment]
@bubenkoff yes I have `translate_tabs_to_spaces` on, turning it off, the line jumping stops.

**Comment by bubenkoff** [comment]
yes it should be on, otherwise it will have the opposite effect
can you try to run the expand tabs command manually and check if it moves the scroll as well?

**Comment by upwebdesign** [comment]
@bubenkoff Im not sure how to run your package in SLT console...

**Comment by bubenkoff** [comment]
command control p - then type indentation: convert to spaces

**Comment by upwebdesign** [comment]
@bubenkoff Yes, when running the command, it still jumps up.

**Comment by bubenkoff** [comment]
i guess, it's then a topic for creating an issue in sublime support

**Comment by upwebdesign** [comment]
@bubenkoff ok, I have three different builds of SLT 3 and they all do the same thing. Maybe there is another package that is cause the issue with your package.

**Comment by bubenkoff** [comment]
are you on dev channel?

**Comment by upwebdesign** [comment]
Im not even sure what that means, dev channel.

**Comment by bubenkoff** [comment]
https://www.sublimetext.com/3dev

**Comment by upwebdesign** [comment]
@bubenkoff, no, I tend to stay on the normal releases. My SLT 3 version on my laptop is `Build 3083` with the same issue

**Comment by bubenkoff** [comment]
can you maybe just try dev to make sure it's still an issue? because for me it's not the case build 3113

**Comment by upwebdesign** [comment]
@bubenkoff I downloaded and installed dev build 3113 and still have the same issue. Maybe its related to another package being installed or my version of my Mac operating system?

El Capitan 10.11.4

**Comment by bubenkoff** [comment]
could be, but just hard to imagine which

**Comment by julesmoretti** [comment]
@bubenkoff - did you guys figure out how to prevent this jumping action? I get the same behavior on Sublime Text 3 for mac, fresh install. And I only have the following in my user preferences:

```
// Settings in here override those in "Default/Preferences.sublime-settings",
// and are overridden in turn by file type specific settings.
{
	"always_show_minimap_viewport": true,
	"detect_indentation": false,
	"draw_minimap_border": false,
	"draw_white_space": "all",
	"convert_tabspaces_on_save": true,
	"highlight_line": true,
	"tab_size": 2,
}

```

**Comment by upwebdesign** [comment]
Nope, still tolerating the line jumps.

**Comment by IllyaMoskvin** [comment]
I have had this issue when using Sublime's built-in command `Convert Indentation to Spaces` manually, before installing this plugin. I suspect it's a bug with ST3 itself. AFAICT, it's just a visual bug, i.e. no actual lines are being added, it's just the scrolling view that scrolls a line upwards. I have no idea as to the precise cause of the bug, though.

**Comment by bubenkoff** [comment]
@IllyaMoskvin thanks for confirmation

**Comment by john-cj** [comment]
https://github.com/SublimeTextIssues/Core/issues/1594
